name: Test

# Controls when the workflow will run.
on:
  # Trigger the workflow on all pushes, except on tag creation.
  push:
    branches:
      - main
      - pre-release
    tags-ignore:
      - "**"

  # Trigger the workflow on all pull requests.
  pull_request: ~

  # Allow workflow to be dispatched on demand.
  workflow_dispatch: ~

jobs:
  docs:
    name: Documentation
    uses: zammad/zammad-documentation/.github/workflows/docs.yml@pre-release
